export { loadTemplateScripts, WORKSPACE_TEMPLATE_VERSION } from "@surreal-ck/shared/workspace-template";
export { ensureSystemSchema } from "./db/system-schema";
export { handleError } from "./middleware/error";
export type { AppBindings } from "./hono-types";
export { createActivationSummaryRoutes } from "./routes/activation-summary";
export { ActivationSummaryService } from "./activation-summary/service";
export { SurrealActivationSummaryStore } from "./activation-summary/store";
export { OpsFollowUpService } from "./ops-follow-up/service";
export { SurrealOpsFollowUpStore } from "./ops-follow-up/store";
export { OpsProposalService } from "./ops-proposal/service";
export { SurrealOpsProposalStore } from "./ops-proposal/store";
export { OpsAutonomyService } from "./ops-autonomy/service";
export { SurrealOpsAutonomyStore } from "./ops-autonomy/store";
export { OpsRunService } from "./ops-run/service";
export { SurrealOpsRunStore } from "./ops-run/store";
export { ExternalOpsAgentRunner, type OpsMcpPort } from "./ops-run/runner";
export { InMemoryPlatformContentStore, PlatformContentService } from "./content/service";
export { createContentMcpRoutes } from "./ops/mcp/routes";
export { createPlatformOperatorCapabilityReader, requirePlatformOperator } from "./ops/operator-auth";
export { env } from "./env";
